Properties
spring.application.name=spring02
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Conexión a PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.baqslpdsvnlddsosxwkf
spring.datasource.password=Auokuls4FXpdR2Ws
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate crea las tablas automaticamente al arrancar

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



server.port=8080